import Foundation

/**
 A type that can be represented by a key path structure
 */
public protocol ModelProtocol: ModelInstance, ObservableObject {

    /**
     The type that contains the ids of all properties of the model.
     */
    associatedtype PropertyId: RawRepresentable & CaseIterable where PropertyId.RawValue == Int, PropertyId: CaseIterable

    /**
     The unique ID of this model class when used in a key path.

     The model id is the first part of a key path.
     */
    static var modelId: ModelKey { get }

    /**
     Run a generated command.

     This function is used to run a command on the instance that was generated using a function generated by `@Command`.
     - Warning: This function is usually called from a `StateClient` and not by the user.
     */
    func execute(command: CommandExecutor) throws

    /**
     Access the values for all property updates.

     This function is called on an instance when a `StateClient` is requested to provide updates of the instance.
     During the function call the instance is invoked with a custom database that records the values.
     - Note: This function is called by `StateClient` and generated by `@Model`. It does not need to be called manually.
     */
    func accessAllPropertiesForUpdateCalculation()

    /**
     Apply updates to the instance.

     This function is called on an instance when updates are inserted via a `StateClient`.
     It gets all available property updates from the executor and inserts them into the database.
     - Note: This function is called by `StateClient` and generated by `@Model`. It does not need to be called manually.
     */
    func apply(update: InstanceUpdateExecutor) throws

}

extension ModelProtocol {

    public func execute(command: CommandExecutor) throws {
        throw StateError.unknownCommandId(command.id)
    }
}

extension ModelProtocol {

    /**
     Create the full path to a property of this instance.

     - Parameter property: The id of the property.
     - Returns: The full path associated with the property.
     */
    public func path(of property: PropertyKey) -> Path {
        .init(model: Self.modelId, instance: id, property: property)
    }

    /**
     Create the full path to a property of this instance using a property enum.

     - Parameter property: The id of the property.
     - Returns: The full path associated with the property.
     */
    public func path<T: RawRepresentable>(of property: T) -> Path where T.RawValue == PropertyKey {
        self.path(of: property.rawValue)
    }

    /**
     Get the value of a property.
     - Parameter property: The id of the property to get
     - Parameter type: The type of the property, if it can't be inferred
     - Returns: The current value of the property, or `nil`
     - Warning: This function is required by the `StateModel` framework and does not usually need to be called directly.
     */
    @inline(__always)
    public func get<T: DatabaseValue>(_ property: PropertyKey, of type: T.Type = T.self) -> T? {
        database.get(model: Self.modelId, instance: id, property: property)
    }

    /**
     Get the value of a property.
     - Parameter property: The enum case of the property to get
     - Parameter type: The type of the property, if it can't be inferred
     - Returns: The current value of the property, or `nil`
     - Warning: This function is required by the `StateModel` framework and does not usually need to be called directly.
     */
    @inline(__always)
    public func get<T: DatabaseValue, P: RawRepresentable>(_ property: P, of type: T.Type = T.self) -> T? where P.RawValue == PropertyKey {
        get(property.rawValue, of: type)
    }

    @inline(__always)
    func set<T: DatabaseValue>(_ value: T, for property: PropertyKey, of type: T.Type = T.self) {
        database.set(value, model: Self.modelId, instance: id, property: property)
    }

    public func all(in database: Database) -> [Self] {
        database.all(model: Self.modelId) { instanceId, status in
            guard status == .created else {
                return nil
            }
            return Self(database: database, id: instanceId)
        }
    }

    @inline(__always)
    static func statusPath(for instance: InstanceKey) -> Path {
        .init(model: modelId, instance: instance)
    }

    /**
     Retrieve the current status of the instance from the database.
     */
    public var status: InstanceStatus {
        self.get(PropertyKey.instanceId) ?? .created
    }

    /**
     Delete the instance from the database.

     This function has no effect for deleted and non-existant instances.
     */
    public func delete() {
        guard let status: InstanceStatus = get(PropertyKey.instanceId), status == .created else { return }
        set(InstanceStatus.deleted, for: PropertyKey.instanceId)
    }

    /**
     Insert a previously deleted model.

     This function has no effect for non-deleted instances.
     */
    public func insert() {
        guard status == .deleted else { return }
        set(InstanceStatus.created, for: PropertyKey.instanceId)
    }
}
